name: Tests STD-List

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer dépendances frontend
        working-directory: ./front
        run: npm install

      - name: Build frontend
        working-directory: ./front
        run: npm run build

      - name: Lancer tests Cypress
        working-directory: ./front
        run: npx cypress run
